name: curve-metaregistry

plugins:
  - vyper
  - alchemy
  - hardhat

ethereum:
  default_network: mainnet-fork
  mainnet_fork:
    default_provider: hardhat

hardhat:
  port: auto
  fork:
    ethereum:
      mainnet:
        upstream_provider: geth
        # upstream_provider: alchemy

geth:
  ethereum:
    mainnet:
      uri: http://localhost:9090
